server:
  port: 10011
  servlet:
    content-type: text/html
logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/agricultural_share?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&amp;verifyServerCertificate=false
    url: jdbc:mysql://120.77.215.43:3306/agricultural_share?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: Ali123456.
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
        cache: false
        mode: HTML5
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

